FROM python:3.3.6

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY . .

RUN useradd -ms /bin/bash app
USER app

CMD [ "uwsgi", "--ini", "/usr/src/app/wsgi.ini" ]
